### ISSUE TITLE
vue 404 when requesting a direct url

### ISSUE THREAD

**Issue by Kreijstal** [ReDI-School/java-intermediate-berlin-2019-spring-website#19]
When you request a page it loads the page but then it errors a 404 not found
for example try loading the [following page](https://redi-java2.netlify.com/lessons/09-oop-classes-and-objects/)

**Comment by maciejwalkowiak** [comment]
I noticed that. Would you like to submit a pr with fix?

**Comment by Kreijstal** [comment]
I guess I can but I'd have to learn vuepress

**Comment by maciejwalkowiak** [comment]
I'll have a look at it today

**Comment by maciejwalkowiak** [comment]
Use small caps in filenames - no 404s then.
